version: "3"

services:
  web:
    container_name: money-tracker-web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./apps/web:/app/apps/web
  api:
    container_name: money-tracker-api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile.dev
    ports:
      - 5000:5000
    volumes:
      - ./apps/api:/app/apps/api
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

volumes:
  mongo-data:
    driver: local
