services:
  - type: web
    name: money-tracker-web
    env: docker
    rootDir: ./apps/web
    dockerfilePath: ./Dockerfile.prod
    dockerContext: .
    domains:
      - money-tracker.render.com
    region: frankfurt
    repo: https://github.com/pt232/money-tracker.git

  - type: web
    name: money-tracker-api
    env: docker
    rootDir: ./apps/api
    dockerfilePath: ./Dockerfile.prod
    dockerContext: .
    envVars:
      - key: MONGO_URL
        sync: false
    domains:
      - money-tracker-api.render.com
    region: frankfurt
    repo: https://github.com/pt232/money-tracker.git
