FROM node:18.13.0-alpine AS builder
RUN apk add --no-cache libc6-compat
RUN apk update
WORKDIR /app

RUN npm i --global turbo
COPY . .
RUN turbo prune --scope=money-tracker-api --docker

FROM node:18.13.0-alpine AS installer
RUN apk add --no-cache libc6-compat
RUN apk update
WORKDIR /app

COPY --from=builder /app/out/json/ .
COPY --from=builder /app/out/package-lock.json ./package-lock.json
RUN npm i

COPY --from=builder /app/out/full/ .
COPY turbo.json turbo.json

FROM node:18.13.0-alpine AS runner
WORKDIR /app

COPY --from=installer /app .

EXPOSE 5000
CMD ["npm", "run", "dev", "--prefix", "apps/api"]